#!/usr/bin/env python

"""Generate random, easy to type letter sequences.

Usage:
  randname <num_letters>

Options:
  -h --help     Show this screen.
  --version     Show version.

"""
from docopt import docopt
from castus.random import randname

if __name__ == '__main__':
    arguments = docopt(__doc__, version='randname 1.0')
    print randname(int(arguments['<num_letters>']))

